### ISSUE TITLE
2015-7-17

### ISSUE THREAD

**Issue by iuphero** [iuphero/Blog#5]
案例研究对于经济学的重要性，数理符号与真实体验
工业革命/产业革命中的劳动力变迁问题
向上倾斜的需求曲线
Veblen effect
冥想与思维浪费
撒旦教

---

En
次品，差的
补助
均衡
过剩地，顺差

**Comment by xfight0** [comment]
surplus
剩余的；过剩的
剩余；[贸易] 顺差

equilibrium

complement ['kɑmplɪmɛnt]
n. 补语；余角；补足物
vt. 补足，补助
complement system 求补系统
object complement 宾语补足语；宾补

inferior [ɪn'fɪərɪə]
adj. 差的；自卑的
n. 下级；次品

**Comment by iuphero** [comment]
经济学研究的最好示范，我始终相信，不是数学模型，不是计量经济学，而是案例研究。  
科斯写案例马歇尔传记的经历  
因为，我们必须关注案例的各方面的线索，从中感受可能带来重要性感受的线索。  
一个案例研究，完全可见研究者对乡土社会的整体理解和社会科学理论的把握  
数理符号是柏拉图描述的迷药，它使大多数读者和作者误以为符号涵盖了真实体验  
时刻返回生活常识的原则，绝不放弃知识对生活的敏感性      

工业革命造成的农民失业，这些人（如砸机器的路德派）如何转换职业？  
有没有造成社会波动  
当今，用机器人取代农民工，这些人又何去何从  

铅笔社也是一个文章共同体，思想共同体  

古典经济学家早就讨论过向上倾斜的需求曲线，经典的例子如“对宝石的需求”，所谓“炫耀性需求”。对这类物品或服务的需求之所以会越贵越求，是因为需求者把代价本身看作可资炫耀的资本。现代的例子甚至更普遍，例如，我们在股票市场上看到的是普遍的行为——追涨杀跌。

[Veblen effect](http://wiki.mbalib.com/wiki/%E5%87%A1%E5%8B%83%E4%BC%A6%E6%95%88%E5%BA%94)

人绝大部分的时间和思维都被浪费在没有成效的思维中，一个数字是47%。
冥想提供了退后一部的可能，平静地观察我们的思维，以一种客观的角度。
冥想就是专注力训练

撒旦教其终极价值观，便是颠覆慈悲与自律的恶魔主义，亦即规避崇高，否认救赎，并极力诉求“丛林法则”下的生存哲学与欲望膨胀，毫无基督教那种“神爱世人”的大爱情怀。

**Comment by iuphero** [comment]
### 中文

浮皮潦草  
徒事干谒、挥霍成习

### En

surplus
剩余的；过剩的
剩余；[贸易] 顺差

equilibrium

complement ['kɑmplɪmɛnt]
n. 补语；余角；补足物
vt. 补足，补助
complement system 求补系统
object complement 宾语补足语；宾补

inferior [ɪn'fɪərɪə]
adj. 差的；自卑的
n. 下级；次品
